{
 "title": "Ingest Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Total out",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "kxi_rt_out_messages_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total in ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "kxi_rt_in_messages_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "RT messages in by publisher",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by(directory) (kxi_rt_in_messages)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}