services:
  kxi-gw:
    image: ${kxi_img_gw}
    hostname: kxi-gw
    user: "${DOCKER_UID:-65534}:${DOCKER_GID:-65534}"
    env_file:
      - license.env
    ports:
      - ${kxi_port_gw_qipc}:${kxi_port_gw_qipc}
      - ${kxi_port_gw_http}:${kxi_port_gw_http}
    environment:
      - KXI_SG_METRICS_ENABLED=false
      - KXI_SG_METRICS_ENDPOINT=/metrics
      - KXI_SG_METRICS_PORT=8081
      - GATEWAY_QIPC_PORT=${kxi_port_gw_qipc}
      - GATEWAY_HTTP_PORT=${kxi_port_gw_http}
      - KXI_SG_RC_ADDR=kxi-rc:${kxi_port_rc}
      - KXI_LOG_FORMAT=${kxi_log_format}
      - KXI_LOG_LEVELS=default:${kxi_log_level}
      - KXI_SECURE_ENABLED=0
      - KXI_SG_USE_SSL=0
      - KXI_SG_CORS_ENABLED=false
    networks: [kx]

  # Resource Coordinator service
  kxi-rc:
    image: ${kxi_img_rc}
    hostname: kxi-rc
    user: "${DOCKER_UID:-65534}:${DOCKER_GID:-65534}"
    env_file:
      - license.env
    environment:
      - KXI_SECURE_ENABLED=0
      - KXI_NAME=kxi-rc
      - KXI_PORT=${kxi_port_rc}
      - KXI_LOG_FORMAT=${kxi_log_format}
      - KXI_LOG_LEVELS=default:${kxi_log_level}
      - KXI_ALLOWED_SBX_APIS=${kxi_apis}
    networks: [kx]

  # Aggregator service
  kxi-agg:
    image: ${kxi_img_agg}
    user: "${DOCKER_UID:-65534}:${DOCKER_GID:-65534}"
    env_file:
      - license.env
    environment:
      - KXI_NAME=kxi-agg
      - KXI_PORT=${kxi_port_agg}
      - KXI_SG_RC_ADDR=kxi-rc:${kxi_port_rc}
      - KXI_LOG_FORMAT=${kxi_log_format}
      - KXI_LOG_LEVELS=default:${kxi_log_level}
      # - KXI_CUSTOM_FILE=/mnt/config/src/agg/custom.q  # Optional for custom APIs
    networks: [kx]
    volumes:
      - ${kxi_dir_config}:/mnt/config
      - ${kxi_dir_pkgs}:/opt/kx/packages
    # deploy:  # Optional: deploy multiple replicas.
    #   mode: replicated
    #   replicas: 1

  # Sidecars for gathering metrics. Can be removed if not needed.
  rc-sidecar:
    image: ${kxi_sidecar}
    user: "${DOCKER_UID:-65534}:${DOCKER_GID:-65534}"
    env_file:
      - license.env
    environment:
      - KXI_CONFIG_FILE=/sidecar-cfg/rc-config.json
      - KXI_LOG_CONFIG=/sidecar-cfg/qlog.json
    volumes:
      - ${kxi_dir_sidecar_cfg}:/sidecar-cfg/
    command: -p 8080
    networks: [kx]
  agg-sidecar:
    image: ${kxi_sidecar}
    user: "${DOCKER_UID:-65534}:${DOCKER_GID:-65534}"
    env_file:
      - license.env
    environment:
      - KXI_CONFIG_FILE=/sidecar-cfg/agg-config.json
      - KXI_LOG_CONFIG=/sidecar-cfg/qlog.json
    volumes:
      - ${kxi_dir_sidecar_cfg}:/sidecar-cfg/
    command: -p 8080
    networks: [kx]

networks:
  kx:
    external: true
