# Default values for kxi-sp.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# -- This sets the `replicaSet` count.
# More information can be found here: https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/
replicaCount: 1

# -- Default image repository and pull settings for SP chart components.
# Refer to Images https://kubernetes.io/docs/concepts/containers/images/
# @default -- `{}`
image:
  # -- Image repository.
  # @default -- `"portal.dl.kx.com/"`
  repository: "portal.dl.kx.com"

  # -- Image component.
  # @default -- `".Chart.Name"`
  component: ""

  # -- Image pull policy.
  # Refer to Image Pull Policy https://kubernetes.io/docs/concepts/containers/images/#image-pull-policy
  pullPolicy: "IfNotPresent"

  # -- Image tag.
  # @default -- `".Chart.AppVersion"`
  tag: ""

# -- Setup Environment variables here for the SP container.
# @default -- `[]`
env: []

# Configure persistence within chart..
# @default -- `{}`
persistence:
  # -- Enable persistence within release.
  enabled: false
  # -- Set this if you want to use a specific storage class.
  # storageClassName:
  #  checkpointDir: /sp/checkpoints
  #  controllerCheckpointFreq: 5000
  #  workerCheckpointFreq: 5000
  #  storage: 20Gi # Storage allocated to each worker/controller

# -- Image pull secrets to be applied to all pods within the chart.
# For pulling an image from a private repository.
# Refer to Image Pull Secrets https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
# @default -- `[]`
imagePullSecrets: []

# -- Override Chart name.
# Used when generating resource names.
nameOverride: ""

# -- Override the default fully qualified app name.
# By default resources are named using `<.Release.Name>-<.Chart.Name>`.
# Used when generating resource names.
fullnameOverride: ""

# -- Can provide any valid `q` runtime argument here.
# Full details here: https://code.kx.com/q/basics/cmdline/
# **NOTE** the `-p` argument will be overridden by the `KXI_PORT` env variable.
args:
  - -kube
  - -g
  - "1"
  - -p
  - "5000"

# -- Configure `ServiceAccount` to be used within chart.
# Refer to Service Accounts https://kubernetes.io/docs/concepts/security/service-accounts/
# @default -- `{}`
serviceAccount:
  # -- Specifies whether a Service Account should be created.
  create: true

  # -- Automatically mount a Service Account's API credentials.
  autoMount: true

  # -- Custom annotations to add to the Service Account.
  # Dictionary of key-value pairs.
  # Refer to Object Annotations https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
  # @default -- `{}`
  annotations: {}

  # -- The name of the Service Account to use.
  # If not set and create is `true`, a name is generated using the fullname template.
  name: ""

# -- Custom annotations to be applied to Pod resources.
# Dictionary of key-value pairs.
# Refer to Object Annotations https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
# @default -- `{}`
podAnnotations: {}

# -- Custom labels to be applied to Pod resources.
# Dictionary of key-value pairs.
# Refer to Object Labels https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
# @default -- `{}`
podLabels: {}

# -- Pod Level Security Context - Configure the Pod Security Context.
# Refer to Pod Security Context https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-pod
# @default -- `{}`
podSecurityContext:
  fsGroup: 65534
  runAsUser: 65534
  runAsNonRoot: true

# -- Container Level Security Context - Configure the Container Security Context.
# Refer to Security Context https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-container
# @default -- `{}`
securityContext:
  readOnlyRootFilesystem: false
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL

# -- Provisions the Kubernetes Service required to expose the workloads.
# This is for setting up a service more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/
# @default -- `{}`
service:
  # -- This sets the Service type.
  # Setting the type field to `LoadBalancer` provisions a load balancer for your Service.
  # The actual creation of the load balancer happens asynchronously, and information about the provisioned balancer is published in the Service's `.status.loadBalancer`.
  # More information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types
  type: "ClusterIP"

  # -- Set exposed Service Port.
  # Refer to Service Ports https://kubernetes.io/docs/concepts/services-networking/service/#field-spec-ports
  port: 5000

# -- You must set your license name.
# Available types are:
#  - `"kc.lic"`
#  - `"k4.lic"`
#  - `"kx.lic"`
kxLicenseName: "kc.lic"

# -- Resource Coordinator Kubernetes resources.
# Refer to Container Resources https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: "100m"
  #   memory: "128Mi"
  # requests:
  #   cpu: "100m"
  #   memory: "128Mi"

# -- Configure Liveness Probe for chart.
# Refer to Configure Probes https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/
# @default -- `{}`
livenessProbe:
  # -- Defines a probe of type `"httpGet"`.
  # @default -- `{}`
  httpGet:
    # -- Path to access on the HTTP server.
    path: "/"

    # -- Name or number of the port to access on the container.
    port: 5000

# -- Configure Readiness Probe for chart.
# Refer to Configure Probes https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/
# @default -- `{}`
readinessProbe:
  # -- Defines a probe of type `"httpGet"`.
  # @default -- `{}`
  httpGet:
    # -- Path to access on the HTTP server.
    path: "/"

    # -- Name or number of the port to access on the container.
    port: 5000

# -- Additional volumes on the output Deployment definition.
# @default -- `[]`
volumes: []
# - name: foo
#   secret:
#     secretName: mysecret
#     optional: false

# -- Additional volumeMounts on the output Deployment definition.
# @default -- `[]`
volumeMounts: []
# - name: foo
#   mountPath: "/etc/foo"
#   readOnly: true

# -- Allows adding node selector constraints to a Pod.
# This constrains the pods to run only on nodes that match the specified labels.
# Dictionary of key-value pairs.
# Refer to NodeSelector https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#nodeselector
nodeSelector: {}

# -- This is for setting Kubernetes Tolerations to a Pod
# This allows the pods to be scheduled on nodes with matching taints.
# Refer to Taint and Tolerations https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/
# @default -- `[]`
tolerations: []

# -- This is for setting Kubernetes Affinity to a Pod.
# Refer to Pod Affinity https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#affinity-and-anti-affinity
# @default -- `{}`
affinity: {}

# -- Default Sidecar configuration for SP components
# @default -- `{}`
kxiSidecar:
  # -- This sets overriding container image information. Use if you wish to target specific versions of the kxiSidecar.
  # More information can be found here: https://kubernetes.io/docs/concepts/containers/images/
  # @default -- `{}`
  image:
    # -- Image tag.
    tag: "1.19.2"
