apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "kxi-gw.fullname" . }}-agg
rules:
  - apiGroups: [""]
    resources: ["pods", "services"]
    verbs: ["get", "watch", "list"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "kxi-gw.fullname" . }}-agg
subjects:
  - kind: ServiceAccount
    name: {{ include "kxi-gw.fullname" . }}-agg
    apiGroup: ""
roleRef:
  kind: Role
  name: {{ include "kxi-gw.fullname" . }}-agg
  apiGroup: ""
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kxi-gw.fullname" . }}-agg