apiVersion: v1
kind: Service
metadata:
  labels:
  name: {{ include "kxi-db.fullname" . }}-da
  {{- with .Values.kxiDa.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "kxi-db.da.labels" . | nindent 4 }}
    app: {{ include "kxi-db.fullname" . }}-da
spec:
  type: ClusterIP
  ports:
    - name: http-metrics
      port: 8080
      protocol: TCP
      targetPort: http-metrics
    - name: rdb-metrics
      port: 8081
      targetPort: 8081
    - name: idb-metrics
      port: 8082
      targetPort: 8082
    - name: hdb-metrics
      port: 8083
      targetPort: 8083
  selector:
    {{- include "kxi-db.da.selectorLabels" . | nindent 4 }}