apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kxi-db.fullname" . }}-sm-sidecar
  labels:
    {{- include "kxi-db.sm.labels" . | nindent 4 }}
data:
{{ include "sidecar.configJson" (list . (dict "connPortList" .Values.sidecar.connPortList)) | indent 2 }}
